stages:
  ingest:
    cmd: python -m src.main ingest
    deps:
    - config/config.yaml
    - data
    - src/core/logger.py
    - src/core/utils.py
    - src/main.py
    - src/pipeline/ingestor.py
    outs:
    - storage/chunks.json
  index:
    cmd: python -m src.main index
    deps:
    - config/config.yaml
    - src/core/logger.py
    - src/core/utils.py
    - src/main.py
    - src/pipeline/indexer.py
    - storage/chunks.json
    outs:
    - storage/vector_db
  search:
    cmd: python -m src.main search
    deps:
    - config/config.yaml
    - src/core/logger.py
    - src/core/utils.py
    - src/main.py
    - src/pipeline/searcher.py
    - storage/vector_db
  answer:
    cmd: python -m src.main answer
    deps:
    - config/config.yaml
    - src/core/logger.py
    - src/core/utils.py
    - src/main.py
    - src/pipeline/answerer.py
    - src/pipeline/searcher.py
    - storage/vector_db
