stages:
  ingest:
    cmd: python -m src.main ingest ${user_id}
    deps:
    - config/config.yaml
    - data/${user_id}/
    - src/core/logger.py
    - src/core/utils.py
    - src/main.py
    - src/pipeline/ingestor.py
    outs:
    - storage/chunks_${user_id}.json
  index:
    cmd: python -m src.main index ${user_id}
    deps:
    - config/config.yaml
    - src/core/logger.py
    - src/core/utils.py
    - src/main.py
    - src/pipeline/indexer.py
    - storage/chunks_${user_id}.json
    outs:
    - storage/vector_db
  search:
    cmd: python -m src.main search ${user_id}
    deps:
    - config/config.yaml
    - src/core/logger.py
    - src/core/utils.py
    - src/main.py
    - src/pipeline/searcher.py
    - storage/vector_db
  answer:
    cmd: python -m src.main answer ${user_id}
    deps:
    - config/config.yaml
    - src/core/logger.py
    - src/core/utils.py
    - src/main.py
    - src/pipeline/answerer.py
    - src/pipeline/searcher.py
    - storage/vector_db
