paths:
  data_dir: data
  storage_dir: storage
  chunks_file: storage/chunks.json
  vector_db: storage/vector_db
models:
  embedding_model: all-MiniLM-L6-v2
  llm_model: mistral
chunking:
  chunk_size: 500
  chunk_overlap: 50
search:
  top_k: 3
